---
title: "Model"
author: "SB Post"
output: pdf_document
bibliography: /home/post/university/collection.bib
biblio-style: apalike
---

# Model

The approach taken in this paper is related to the "O-ring" theory of economic development from @kremer_o-ring_1993. The O-ring model focus on risks in the production process: a single mistake in one of $n$ sequential tasks in the production process - like the failure of the O-ring that caused the *Challenger* space shuttle catastrophy - ruins the entire production. While Kremer's work show how such production risks lead firms to match the skill of employees, I am interested in the role of disruptions in production networks in determining the products that firms choose to produce. 

In this section I first ... I then discuss how the addition of production networks and I/O relationships into the simple model can propagate risk and nifluence the choices of firms. 

Say that each firm produces a single product. The output of a firm can be used as intermediate inputs in other firms production in the next time period. In each time-period, a firm needs to have some measure of capital, some labor, and some intermediate inputs to have a successful production. For the moment, keep capital and labor the same across all firms. Firms can choose to produce more or less complex products. Each product requires a number of inputs to be successfully delivered to the firm to be successfully produced. In this simple model, more complex products requires a larger number of inputs (and are in turn more valuable). We can denote the complexity of the product by the number of inputs necessary for successful production $\tau$. 

TODO 1:
It is possible for firms to "over compensate" their input sourcing by investing (at a small cost) in collecting more inputs than $\tau$. The ... model is essentially a balls-and-urn problem. 

TODO 2:
In a world with no disruptions to productions firms always get to $\tau$, there are no unsuccessful productions, and there is no risk in increasing the complexity of the products. However, if we add 

@brummitt_contagious_2017 show that the sourcing relationships in such a model spreads the dysfunction between firms. If the share of unsuccessful productions reaches some threshold^[Depending on the cost of input-buffers, the utility added by more complex products, etc.] firms, should they acts a self-optimising agents, will choose to produce less complex products. Their modeling-results suggest that, given their (rather extensive) simplifications, a poverty-trap style effect can emerge: in response to disruptions to the production process, firms choose to produce simpler (and less valuable) products in order to function. The disruptive environment also punish firms trying to bypass the complexity frontier. If suppliers tend to have unsuccessful productions, firms with a markedly higher $\tau$ will not only suffer input-sourcing costs, but will find it very difficult to achieve a successful production and having any output at all. This means that ... TODO 


Supply networks, however, are very much not random. Since Leontief (xxxx) the importance of the structure of the relationship between sectors have been recognized. More recent studies have shown how the organization of input-output networks affect the vulnerability of economies to aggreagate shocks, 

























Where Kremer's model assumes that more complex production processes takes in more tasks, and risk therefor is related to the quality of the workers undertaking each task, 

Instead of focusing on the risk of each productions $n$ tasks and the risk of workers "messing them up", I focus on exogenous disruptions to the production process. 


The O-ring production function in Kremer (): Each firm combines some amount of capital (K) with a group of $n$ workers or tasks. Each task has $q$ probability of being produced accurately. If an error happens (food spoil, vases are dropped, wood is mishandled) the production output is 0. I the long run, $q$ thus represents the value of a given worker to the production output.

The expected output of a production is thus:

$$
E(y) = k^{\alpha} (\prod^{n}_{i = 1} q_i) n B
$$

There are $n$ different firms in the economy. Each 
 
[Husk expectation ide]

$$
x_i = z_{i} k^{\alpha}(\prod_{j = 1}^{n}  x^{w_{ij}}_{ij})
$$

where $k$...


In the case where there exists only one plant in the economy, the only risk of production disruption is $z_i$. However, when we include other firms' output as the source of intermediate inputs, the model begin to resemble Kremer's. Now each other firms risk has to be included into the intermediate input production. That is, each firms expected output has to be deflated by $z_i$. When we include this in the production process, we has to include the temr 

$$
x_i = z_{i} k^{\alpha}(\prod_{j = 1}^{n}  (z_j x_{ij})^w_{ij}
$$


For the sake of illustration, lets abstract away from capital and total factor productivity. Now the output equals the i

Same n, lower z; same z_i, higher n

Hvis firmaet er alene så er det en simpel model, men hvis den er en del af et produktionsnetværk, så er det lig Kremers model.

- BEATS TO HIT:

 - Complex products require more steps and/more inputs and/or longer suppley chains.
 - In simplest form, we can think of the process as a simple ball and urn model. If supply links are selected randomly and all inputs are substitutable, it becomes a binomial distribution.
 - However, links are not random. They are in fact, very far from random - scale free distribution. 

 # References



