* TODO [#C] Introduction

* TODO [#C] Conceptual framework introduction

* TODO [#B] Product complexity

* TODO [#A] Disruptions in an O-ring model
- Mangler at binde den sammen over til supply chains, input substition og I/O netværks

* TODO [#A] METHODs
- Empirical strategy (outline)
- Metrics: PCI
-
* TODO [#B] Data
- [ ] Electricity
- [ ] Weather
- [ ] ASI + IO
- [ ]



* BRUG

- papir til at bruge product complexity measures på.

  - Fra: [[https://www-tandfonline-com.ludwig.lub.lu.se/doi/full/10.1080/1540496X.2018.1443073?scroll=top&needAccess=true][artikel]] "Recently, a new line of research has established a connection between an economy’s growth and the complexity of its products. It proposes that countries have certain comparative advantages or capabilities that determine the complexity of products made at home (Hidalgo 2009; Hidalgo and Hausmann 2009). Moreover, in the context of internationally fragmented production, those country capabilities would determine which production stages are domestically performed. Thus, countries involved in IPNs will have more or less complex parts of the production processes in their export basket depending on their locally available capabilities like technological, human and physical capital and logistic and organizational capability. According to Costinot, Vogel, and Wang (2013), rich countries will be relatively better at producing more complex parts of the transnationally segmented production process, so they tend to specialize in them. These authors consider that less complex parts have a rather high labor cost share, so high-wage, high-productivity countries are less competitive in those parts.1"
    og
  - "Hidalgo (2009) and Hidalgo and Hausmann (2009) consider that product complexity is related to the amount of capabilities or know-how necessary to manufacture products. These authors point out that, first, the complexity of a product is related to the (tangible and intangible) capabilities the product demands and, second, countries and products are involved in a network. They explain that economies which require a large number of capabilities for the production of a good will be economies that are more willing to adapt to changes than those that produce goods that need fewer capabilities and consequently would be less complex. Likewise, they note that the complexity of an economy is related to the characteristics of the network’s structure. In this regard, it would be expected that economies with a greater range of available capabilities would participate in networks that are more complex. They develop the method of reflections where they incorporate the concepts of ubiquity and diversification based on a bipartite network structure. Ubiquity refers to the exclusivity in exporting a product, that is, whether the number of countries exporting it with a comparative advantage is low. The larger the variety of capabilities the product requires, the greater its degree of complexity will be and the smaller the number of countries that export it. Diversification refers to the number of products that an economy exports in conditions of comparative advantage, which is positively related to the variety of capabilities available in that country. The Method of Reflections suggests that countries with a broader set of available capabilities are more likely to have more diversified production structures, which means these countries export more exclusive products (Reinstaller et al. 2012). The Method of Reflections iteratively calculates a measure of complexity that combines both types of information, diversification and ubiquity. The Product Complexity Index (PCI) is constructed by calculating the average diversity of countries that make that product and the average ubiquity of the other products that these countries make.3 The position of a product in the complexity ranking depends on the value of that product in the PCI. The higher the PCI value and the higher the position in the ranking (top places), the more complex the productions are."
