
# Economic complexity

Why be interested in how complex product Indian plants produce? A recent literature on economic capabilities 

xxxx quantifies the sophistication of the productive structure in an economy by exploiting the information on the number of products it exports and the ubiquity of those products (that is, how many countries export them). 

Continuing the LEGO analogy, the product complexity values tells us about the value of the pieces present in the economy. Understanding why an economy has the landscape of LEGOs it possess is an important taks in understanding the opportunities and constraints on its economic development. 



# IN METHODS
The central idea behind the economic complexity approach is that to perform a given economic activity - like produce a product - one must possess a certain number of economic capabilities. 


As such, we can think of the relationship between countries, capabilities, and products as being connected in a tripartite network. We can only observe the countries and the products. While the best specific algorithm to extract information is still under debate, the approach is common. Essentially, two assumptions are made. First, countries possess the capabilities of the products they export and if countries export more complex products, they possess more sophisticated capabilities. Second, products that tend to be exported by more sophisticated countries require more capabilities and are thus more complex.

If we return to the LEGO analogy, this has an important implication. If more sophisticated economies possess more capabilities, they should be able to export more products in general including /both/ high- and low-complexity products. Low-sophistication economies, on the other hand, should only be able export less complex products. This fact is illustrated in figure [TODO xxx]. This means that there is more information the fact that low-sophistication economy exports a product than if a high sophistication does (given that they should be able to export most products). 

I follow the fitness-complexity algorithm developed in tachella... The algorithm follows an iterative process, where each iteration "refines" the information from the earlier by weighting country-values ("fitness") by the complexity of their products and product values by the fitness of the countries that export them. 



