#+TITLE: Two models
#+AUTHOR: Søren Post
#+Options: toc:nil date:nil
#+LATEX_HEADER: \setlength{\parskip}{1em} % set spaces between paragraphs to 1 character
#+LATEX_HEADER: \setlength{\parindent}{0em} % set indents for new paragraphs to 0
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage[a4paper, total={6in, 8in}]{geometry}
#+LATEX_HEADER: \newcommand{\vect}[1]{\boldsymbol{#1}}

\newpage

* Contagious disruptions in a production network

In an model economy, all firms can be either functional or dysfunctional.

Each firm produces a single product. In order to produce this product, a firm needs a number of inputs. If the firm can source the required number of inputs, it is functional and produces a product that can be used by other firms as input. If it does not receive the required number of inputs, it becomes dysfunctional and it does not produce an output.

At any given time $t$ the share of functional firms in the economy is $F(t)$. The share of dysfunctional firms is $1 - F(t)$. A firm tries to get $m$ inputs and needs at least $\gamma$ to be successfully delivered to be functional. $m$ is then the "attempted inputs" and can be thought of as a firms in-degree in an input-output network. $\gamma$ is the threshold level required for a successful production.

- [ ] simplifications



The evolving input-output network (and the disruptions) can thus be expressed through the differential equation for the expected share of functional firms at a given time:

\[ \frac{dF}{dt} = P[Binomial(m, F(t)) \geq \gamma - F(t) \]

for $t \geq 0$ and integers $m \geq 0$ and $\gamma > 0$. When $\gamma = 0$ no firms require any inputs to their production and the model is nonsensical no firms require any inputs to their production and the model is nonsensical.

For simplicity, in each production attempt, inputs are chosen randomly (uniformly) with replacement from the population of firms. The idea is that firms do different tasks, requiring different inputs: an engineer fixes a machine on Monday, leads a meeting on Wednesday, etc (assumption is relaxed later).

All firms use the same values of $m$ and $\gamma$. Therefor the probability of a successful production is that a binomial random variable with parameters $m$ (tries) and $F(t)$ (probability of success) is larger or equal to $\gamma$ (number of critical inputs necessary for success). This means that firms can have buffers. That is, the amount $m$ is greater than $\gamma$ is the "redundancy".

Some disruptions are exogenous. Fires, insect outbreaks, weather, etc. These effects are introduced in the model as $\epsilon$. Each firm is disrupted individually and becomes dysfunctional a small rate (Poisson process). This introduces $- \epsilon F(t)$ to the differential equation as the number of functional firms that are disrupted by $\epsilon$ at time $t$:

\begin{align*}
\frac{dF}{dt} &= [1 - F(t)]P - F(t)(1 - P + \epsilon) \\
              &= P - F(t)(1 + \epsilon)
\end{align*}

Where P is the probability that a firm successfully produces its output, i.e. $P[Binomial(m, F(t)) \qeq \gamma]$

We can de-compose the equation above into separate terms. The first term, $1 - F(t)$ represents the rate at which dysfunctional firms attempts to produce. For each attempt, there is P probability of success. If the attempt is success, F(t) rises, if not, F(t) stays the same. The second term, $F(t)(1 - P + \epsilon)$ is the reverse. F(t) is the number of functional firms that attempt to produce. 1 - P + error is the 1 minus the probability of success, that is, the probability of dysfunction, plus til exogenous risk of dysfunction. The first term is then hos many dysfunctional firms become functional, the second hos many functional firms become dysfunctional.

The starting conditions, the amount of dysfunction 1 - F(0) is exogenous. Rest of dysfunction is entirely endogenous. All of this dysfunction is driven by the effect that a firm can only deliver the input to other firms if it is successful it the most recent attempt to produce.

*Choosing complexity ($\gamma$) and buffers ($m - \gamma$):* To include the incentive to produce more complex products, a utility function is added, where firms derive utility from producing more goods that require more inputs. This utility is expressed by $\gamma^{\beta}$ where $\beta$ is between 0 and 1. It also assumed that each attempted input has a cost of $\alpha$, wehere $\alpha$ is more than 0. This is the marginal cost of finding a supplier, arranging input, etc. Again for simplicity, it is assumed that each firm knows thew likelihood that a supplier will successfully produce and deliver the required input, F(t). On the basis of this reliability, a form can revise its strategy on how complex the product should be: $\gamma \in \{0, 1, 2, ...\}$, as well as how many inputs should be attempted: $m \in \{0, 1, 2, ...\}$.

Each firm must commit to a product for a certain amount of time $T$, so decisions are updated after every $T$ amount of time (at the same time). They change their behaviour to the "best response", the maximisers  $m*, \gamma*$ of the utility function

\[
U [m, \gamma, F(t); \alpha, \beta] = P[m, \gamma, F(t)]\gamma^{\beta} - \alpha m
\]

It is then define
