* She Comes First

1. Det tager længere tid for kvinder at opnå orgasme. Studier viser at blandt kvinder hvis partnere bruger mere end 21 minutter på forspil, kun 7.7 opnår ikke orgasme. "Postpone pleasure"

2. Clitoris består at hovedet, shaft, base. Og 18 strukturer. Skal ikke tænkes på som en lille kugle, men som et komplext netværk.

3. Yderste 1/3-del er meget mere følsom end inderste. Det giver ikke mening kun at betragte penetration som det centrale i sex.

4. Meget er sagt om forskellen mellem G-spo og klitoris. I virkeligheden er g-punktet måske bare bagsiden af klitoris. Meget af den nydelse der kommer ved vaginal penetration skuldes pres mod den vaginale åbning - "clitoral cuff" og ikke fra ting der sker inden i vagina. Altså: stick to basics - clit.

5. Oral sex er mere end forspil og anderledes en penetrations sex. Har sin egen beretterelse på lige fod ("core play").

6. Lidt historie.

7. Freud hadede klitoris. Det har gjort en masse dårligt for sex rundt i verden. + Ifølge "Cradle of Erotica" så krævede kejserinde Wu Hu (det hedder hun sgu) at government officials og besøgende "dignitaries" viste respekt til hende vd at gå ned på hende. Gamle malerier viser hende stående med åben kåbe, med noblemens knælende foran hede.

8. Vulva bruges om hele molevitten. Vagina er inden i.

9. Yder dele:
   - Mons Pubis: der hvor fedt væv og pubeshår dækker pelvic knogle.
   - Labia Majora: ("ydre læber") ydersiden har hår, indersiden har ikke. Outer lis er tilsvarende mandens scrotum. Ikke så følsomme som indre læber.
   - Font commisure: omårdet mellem mons pubis og "hood". Skjuler clitoral under.
   - Labia minore: "little lips"/"inner lips" omfavner clitoral glands. Som på indersiden af labia majore er der ikke hår, men har "bumps" der er olie-kirtler. Ekstremt sensitive og spiller igtig rolle i at blive opstemt. Størrelsen og form afhænger meget fra kvinde til kvinde.
   - The hood: ydre kanter af inner lips, lige over klitoris ("kvindelig forhud"). Friktionen fra når hood gnubber sig op ad klitoris stimulerer nydele. Besktter også mod overstimulering: lige inden orgasmen så gemmes klitoris hovedet inde i hoodens folder.
   - Fremulum: Efter/under hovedet mødes indre læber hinanden og former frmulum. Meget følsomt.
   - Forchette: Modsatte del af fornt commisure. ER der hvor bunden af læberne mødes.
   - Clitoris glans: ("hovedet") Ikke noget nyt. 18 000 nerveender. Men må ikke undervurdere hvor følsomt den er.
   - Perineum: ("taint") Er følsomt når man bliver opstemt og kan gie højere seksuel lyst når stimuleret. God ide at inkluderer i "travel plans".

10. Interne dele af clitoris:
    - Clitoral body: Shaft går o fra hovedet 3/4 inch mod pelvis, og går ned i et "Y" langs inner lips og omringer to "bulbs" of erective tissue ("clitoral bulbs"). Extremely receptive to sensation.
** 22: Foreplay; reference terms
- Anticipation: skab en stærk følelse af at glæde sig. Banale gestusser: strejt, besked, telefonopkald.
- Undgå: undgår direkte kontakt med kønsorganer i mindst 10-15 minutter under forspil. Stimuler i stedet andre dele af kroppen.
- Awareness: Læg mærke til nuancerne i seksuel resonse - lad være med at miste fokus. Processen skal ikke løbe fra dig. Strukturen er vigtig.
- Bath: Det er vigtig med god hygiejne.
- Barber: stubbles er dårligt.
- Body, hers: Huden er det største seksuelle organ.
- Bryster: bryst-kontakt er vigtigere for mænd end for kvinder. "Savour, don't suckle".
- Breath, yours: Brug mouthwash
- Breathing, hers: de fleste mænd tænker på at det vigtigeste tegn på at en kvinde er tændt er hvor våd hun er. Men det er ikke rigtigt. Der er en sammenhæng, men verjtrækningen er vigtigere.
** 23: Introducing corelay
** 24: Form follows function
** 26: First kiss
