* Bristow and Healy (2018) Innovation and regional economic resilience: an exploratory analysis

- Det er i de seneste år blevet fremhævet hvordan innovation er en af nøglerne til at opnå økonomisk modstandsdygtighed overfor shocks. Dette er i sær udbredt i policy-kredse. Fx EUs SC& advisory group 2014.
- En voksende mængde af forskningspapirer peger også på at innovation er vigtigt for long-term regional "path reneval" og "restructering" der gør det muligt for regioner at tilpasse sig.
- *Innovation kan defineres og måles smalt* ift research & development eller teknologisk innovation (som er associeret med udviklingen af nye produkter). Det er vist i litteraturen at firmer der iverstere mere i udvikling er mere robuste overfor forandinger og bedre til at tilpasse sig. Det er også på linie med det Schumpertske syn på innovation som en drivkraft bag økonomisk forandring (i.e. innovation er en major disruptor af production functions og en kilde til long-run economic transformation).
- *Evolutionary economic geographers" laver forskel mellem resilience baseret på "adaptation" og "adaptability".* "Adaptiation" er tendencen til at genskabe og reproducere eksisterende økonomiske aktiviteter og måder at arbejde på. "Adaptability" er karakterisert af en dynamisk evne til at udvikle og jage nye økonomiske "trajectories" (arh men hvad fanden er det for noget hu ha speak). De steder der har større adaptability er bedre til at klare sig overfor økonomiske shocks. Geograferne understreger innovations kapaciteten som en nøgle i evnten til at tilpasse sig, og dermed genopfinde sig selv i lyset af økonomiske shocks..
- I denne artikel bruges den Europæiske Kommissions Innovation Scoreboard som mål for innovation capacity.

** The role of innovation in resilience: an evolutionary perspective
- *Den evolutionære økonomiske geografi-litteratur er der en stigende konsensus om at regional economic resilience* kan defineres som en regions kapacitet til at modstå, komme sig fra og reorganiserer sig overfor markeds- konkurrence- eller miljø-shocks til regionens vækst-sti. Vi kan således tænke på resilience som bestående af de fire R'er (Se Martin and Sunley 2015):
  - resistance (evne til at modstå shocks) 
  - recovery (evne til at komme hurtigt tilbage til pre-shock state)
  - reorientation (omfanget so regionen tilpasser sin økonomiske struktur)
  - renewal (i hvilken grad regionen genfinder sin preshock path)
- *Der er ikke god forståelse af hvordan disse forskellige elemnter påvirker hinanden.* Man kan fx forestille sig at eb region har hurtigt "bounce-back" ift output, men at dens recovery er baseret på "gamle" teknologier og derved ikke har mulighed for at omstille sig eller at "opgradere". En anden mulighed er at en region som er resistiances gør det præcist fordi den har en adaptiv capacity, der gør at den er i stand til at tilpasse sig og ændrer sig i fremtiden. (Se Boschma 2015)
- *Schumpeter* er bredt refereret ift at udvikle ideen om at teknologisk innovation er driftkraften bag adaptive processe, og derved resilience. Han identificerede en kapitalistisk økonomi som bestående af fire faser: prosperity, recession (fald i økonomien), depression ("below zero decline"), recovery (postiv vækst). Han fremlagde at øget teknologosk innovation gennem depressionsperioden (dvs efter recession) tjente til at afskaffe forældede og uproduktive industrier og praksiser, og at dette skabte muligheder for udviklingen af nye sektorer og vækst-faser. Se fx Simmie 2014b. Dette er kendt som "creative destruction". For en udvikling af Panarchy-model ift Schumpeter, se Simmi and Martin 2010.
- *Related variety og resilience*. Der har ikke været meget forskning i området, men noget tyder på at related variety kan være med til at absorbere en del af shockenes effekt. Fx findes Diodato og Wettering and regioner med mere centrale industrier er mere resilient. Desuden kan man foreestille sig en effekt, hvor det er nemmere for arbejdere at blive absorberede i relaterede industrier.
- *Unrelated variety og resilience*. Andre studier antyder at udvilingen af unrelated activities også er kritisk for adaptabilitiy, fordi det lyder tilteknologiske breakthroughs, og derved åbner nye vækst muliggheder, der er anderledes end de der er ramt af en shock (og derved måske er blevet forældede).
  - *Kreativitet og innovation spiller en vigtig rolle i system-dynamikker og kan betragtes som en art "evolutionær brændstof" i complex systems.* Dette indebærer dog en berede forståelse af innovations kapacitet - ud over teknologiske development, så gælder det også hvorledes innovation bruges og hvordan innovationer påvirker hvordan eksisterende resourcer bruges - i.e. der er altså også en institutionel komponent. 
- *Vi kan tænkte på økonomiske shocks som at de skifter fitness landskabet* og derved skaber nye space of the possible. Hvis man er en økonomi hvor det er lettere at omstille sig, så bliver det i højere grad muligt at flytte sig mod frugtbare steder i det nye fitness landskab. ("possibility mix" og "fitness surface", Cooke 2012)
- *Brugen af employment over GDP* er givtig, dels fordi sociale og politiske preferencer plejer at vægte employment høj som et tegn på en økonomis helbred, dels fordi innovation i en økonomi kan lede til at arbejdsudbuddet i en økonomi falder, selvom GDP stiger. Hvis dette skulle være udfaldet som svar på en shock, så kunne man udefra mene at regionen ikke var resilient, fordi der var blevet så mange nye arbejdsløse. Dette ville være misset under GDP mål.
