* Francis
First of, many of the points here are things I'm also guilty of, it's just easier sometimes to see it someone elses work.

*Conceptual clarity in /your/ use.*
1. I think it could help the reader if you devote a little space to identify how the concepts are used in /your work/. For instance, Green Infrastructure is the central concept that you look at changes in. But you don't mention anything on how the concept is identified by you. It makes sense to star from the EU definition, but I would be interested in how you operationalise it. For example, does it only count when "GI" is specifically mentioned in policy papers and speeches, does all sustainable development-discussions count, and so on.

2. Link different concepts together more clearly, or leave them out. This might just be because of the word-limit, but I think is important either way. For example: you introduce demise of the democratic state, increased financialisation, new urbanism. Even if I have an idea of what how they might influence goverment spending, it is not clear to me that they directly affect green infrastructure. If you make it clearer how exactly the concepts play a role in how you examine them, I think it makes understanding he value of the study much easier. This is related to the point about defining your variable. In what way do you think that "influence" (in the RQ) would be identified? Like, what does it take for state-led privatisation or new spending patterns in government to act on green infrastructure, rather then just co-occur in parallel?

*Structure:*
1. Structure paper more clearly. You introduce decentralisation, state-led privatisation, corporatization of urban governance, etc. But it is only in the last or second to last part of the paper that you tie GI to governments sustainability targets and how these tie into city governance, which has been more important after decentralisation. I think this point should be expanded upon and put much earlier. To me, this seems like the most interesting part. You know, how rolling back the state have given local actors more power, and how this interacts with the sort of everything being tied together by marketisation or whatever. And especially, how the Policy Planning Framework fits into this. 

2. The final thing is related to this. For me, writing in especially critical geography can be very hard to follow. There are a lot of different, a bit vaguely defined concepts that are alle supposed to interact together. So, as a personal opinion, this makes it harder to track the "scientific" contributions in some of the work. So, for me, it would make it much easier to have everything mapped out precisely. Maybe just as a starting point, but like almost comically simple to start with. How are these different factors thought to interact, and so on.  This is to keep avoiding falling into this trap of everything becoming sort of fuzzy concepts, where it feels like I understand what is going on, but actually don't.

* Clara
  RQ: to what extent (and how) does sustainable dev in Norrbotten region follow env. targets in SDGs?

Comments:
- You want to examine the "sustainable development" in some region and analyse how it relates to the SDGs. How do you define what you "look" for as sustainable development? For example, you say you examine natural resource use and nature-based tourism. I assume you will be doing more than just say resource extraction is not very sustainable, environmentally. What I mean is, that you write that you will decompose the Sustainable Development concept to more specif dimensions (economic , social, and environmental), and create measurable indicators from them. But I could be worried that these a A) still very complicated (how do you evaluate economic and social sustainability, fx?) and broad, and b) how do you create measurable indicators for these things that you can employ in document analysis?

- I would work really hard on identifying both the three concepts and how exactly you are thinking about identifying what counts as evidence. If you are mostly analyzing documents or outputs by official sources, you might need to introduce some theoretical work or framework of how to analyze these kinds of sources. You mention thematic coding, but this is perhaps more of a method, than a framework. What I am trying to say, is maybe how to distinguish what you are doing, from somebody who just reads the documents and forms an opinion. 
