#+TITLE: Seminar 3 comments: Kira Uhlin
#+AUTHOR: Søren Post
#+Options: toc:nil date:nil
#+LATEX_HEADER: \setlength{\parskip}{1em} % set spaces between paragraphs to 1 character
#+LATEX_HEADER: \setlength{\parindent}{0em} % set indents for new paragraphs to 0
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage[a4paper, total={6in, 8in}]{geometry}
#+LATEX_HEADER: \newcommand{\vect}[1]{\boldsymbol{#1}}

Word count: 641

\newpage

Hi Kira,

First of all, fantastic title.

I like a lot of things about your project. Your case is both different, interesting, and there seems to be a lot of broader aspects that can examined in it (ethical issues, the "tech fix" to social problems, private distribution of social services, crowding-out effects on local health care provision, etc.). I also think it's a solid approach to sketch out the process going forward. Maybe dating each section would be even better?

I have two general comments. First, you identify that you aim to produce an "elucidation of the main operation" of Zipline. However, through your writing (and what I remember from the previous seminars), it is not exactly clear to me whether you want to create a sort of "evaluation" of their program, or you want to examine broader developmental issues or challenges such an operation presents. Second, my main concern is to how you distinguish your work as being a scientific examination, rather than a "journalistic" investigation. You present a rather broad empirical investigation, and it could be challenging to hit all of the beats thoroughly. That is, if you want to investigate too many things, do each part become superficial?

For instance, in your quantitative analysis you want to examine the efficiency and costs of the operation using some spatial statistical analysis. If the analysis consists of more than just reporting and comparing numbers presented by Zipline itself, this could require a lot of work. For example, how do you identify what is efficient? If, for instance, you build some model of efficiency as health outcomes by costs, you would need to build a counter factual scenario, including considerations of who receives what kinds of services, comparability to public services, etc. An additional point could be the sort of crowding-out or substitution-effects (or even enhancing effects) that a private venture like Zipline could have on the capacity development of public options.

As for the data you want to collect, it is not entirely clear what part each data source plays in your analysis. Perhaps you have addressed this in a conceptual framework, but it might be helpful to clarify the exact contribution of each dimension. For example, when you identify key and interview key representatives in Zipline and within the sector, which part of the operation are you interested in? If it becomes too general, it might become too unfocused. A similar point applies to the quantitative approach.

It seems to me that the company represents a lot of interesting dimensions in the broader development context. From your writing, it seems that you work from a hypothesis-based approach (final part of sources-section). However, you don't identify any such hypothesis (again, you might have addressed this elsewhere). Perhaps it could be an easier approach to choose a specific aspect or theory of the privatization/technology/state capacity/whatever-dimension that the Zipline-operation represents in the larger picture and analyze your case from that approach. That is, go from general trends to the specific.

A few additional points: It seems that Zipline is a major recipient of VC funding. It might be interesting to examine the aspect of a controversial technology (private drone use in public service delivery) being "piloted" in a developing country as a "proof of concept". It could also be interesting to examine the de-politicization that sometimes happens when bureaucratic or technical solutions are applied to development problems. If this is something you are interested in, The Anti-politics Machine by cite:ferguson1994anti (it is also available as a short article) might be interesting. It might also be helpful to look at how other researchers have examined technical solutions to development problems (maybe like mobile 'surveillance' of refugees, the one-laptop-per-child program, block chain technology in property rights).

Good luck!


\newpage

bibliography:SGED07.bib
bibliographystyle:humannat

